name: hacker_news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  hugeicons: ^0.0.11
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  json_serializable: ^6.9.5
  retrofit_generator: ^9.2.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
  
  fonts:
    - family: ChakraPetch
      fonts:
        - asset: assets/fonts/ChakraPetch/ChakraPetch-Bold.ttf
          weight: 700
        - asset: assets/fonts/ChakraPetch/ChakraPetch-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ChakraPetch/ChakraPetch-Medium.ttf
          weight: 500
        - asset: assets/fonts/ChakraPetch/ChakraPetch-Regular.ttf
        - asset: assets/fonts/ChakraPetch/ChakraPetch-Light.ttf
          weight: 300
    - family: Doto
      fonts:
        - asset: assets/fonts/Doto/Doto_Rounded-Black.ttf
          weight: 900
        - asset: assets/fonts/Doto/Doto_Rounded-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Doto/Doto_Rounded-Bold.ttf
          weight: 700
        - asset: assets/fonts/Doto/Doto_Rounded-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Doto/Doto_Rounded-Medium.ttf
          weight: 500
        - asset: assets/fonts/Doto/Doto_Rounded-Regular.ttf
        - asset: assets/fonts/Doto/Doto_Rounded-Light.ttf
          weight: 300
